### ISSUE TITLE
Fix this error..

### ISSUE THREAD

**Issue by ItsTauTvyDas** [grohsfabian/minecraft-servers-list-lite#9]
Can you fix it? In page I have "HTTP ERROR 500", in "php_error.log" file i have this:
```
[24-Sep-2017 09:07:40 UTC] PHP Fatal error:  Uncaught Error: Call to a member function fetch_object() on null in /home/----------/public_html/S/core/functions/general.php:447
Stack trace:
#0 /home/----------/public_html/S/core/init.php(32): settings_data()
#1 /home/----------/public_html/S/index.php(2): include('/home/----------...')
#2 {main}
  thrown in /home/----------/public_html/S/core/functions/general.php on line 447
```

**Comment by grohsfabian** [comment]
Hello,

That means you did not install the script properly. Please make sure your db connection is properly set and that you have the tables and the contents in there.

Regards,

Fabian.
